### PR TITLE
Add function for checking date types

### LINKED ISSUE #47: qtr only accepts lubridate date types
Currently, the `qtr_` functions will only accept a date variable if it is specifically the lubridate `Date` class this is more restrictive than the `fin_year` function, which also accepts dates of `POSIXct` class. This is a bit confusing when you can possibly use one function on a date column but not another function.

I don't see any reason why `qtr_` can't take a `POSIXct` class date column so I suggest making that change, might be nice to create a util function `is_date` which can be used by all other functions.

### PR DESCRIPTION
**Pull request by Moohan**
Resolves #47

### CODE REVIEW

**Review by davidc92 — COMMENTED** [review]
Hi James, before I review this can you please fix the problem that's causing the build to fail with Travis?

**Comment by Moohan** [comment]
> Hi James, before I review this can you please fix the problem that's causing the build to fail with Travis?

That should be it, it just wanted a bit of extra documentation. Sorry, thought I had run a full check before submitting! The checks definitely pass on the server now, so hopefully Travis will report the same shortly!

**Comment by Moohan** [comment]
I've just had a thought that it would probably make more sense to move the whole `if (!is_date(date)) stop("The input must have Date or POSIXct class")` bit into the function so that it could just be used as `is_date(date)`.

Let me know if you want me to refactor like that?

**Comment by davidc92** [comment]
Actually, I've taken a look at what this PR is doing and I don't like creating a new function which is just another function with a different name. If the problem is the error handling in `qtr` is too strict, then can you just add the extra arguments to the `inherits` function rather than wrapping an extra layer of functions around it?

**Comment by Moohan** [comment]
Closing this as there is a simpler fix in #50 as suggested by @davidc92

**Pull request closed without merging**
