### PR TITLE
Remove gdata dependency 

### LINKED ISSUE #91: Remove the dependancy on `{gdata}`
Per [this comment in the RSIP FAQ ](https://github.com/Public-Health-Scotland/R-Resources/blob/master/posit_team_applications_faq.md#how-do-i-install-the-phsmethods-package) I think we could just remove the dependency on `{gdata}`, as it's only used in one place. `{gdata}` imports loads of other dependencies that we don't need at all.

### PR DESCRIPTION
**Pull request by Moohan**
Closes #91 

Just a quick PR to remove the `gdata` dependency, as it's causing issues with installing phsmethods on the new server. I've replaced it with the `scales` package in the one place it was used, and tidied up the code a little bit.

### CODE REVIEW

**Comment by terrymclaughlin** [comment]
@rmccreath James McMahon has removed the dependency on `{gdata}` in the `{phsmethods}` package.  Any idea who would be best placed to review this in Tina's absence?

**Comment by Moohan** [comment]
@terrymclaughlin / @rmccreath / @Tina815 

I don't know if people are still having this issue?

Either way, I think `scales` is probably a better solution than `gdata` as it's more likely to already be installed by users (it's an r-lib package), and it solves the problem directly which makes the `phsmethods` code a bit neater.

If there's no rush for it this PR should probably be re-based to the development branch and just include with the next batch of changes.

**Comment by rmccreath** [comment]
> If there's no rush for it this PR should probably be re-based to the development branch and just include with the next batch of changes.

Hey @Moohan - I'd say that the workaround for utilising `{phsmethods}` is known and your idea is the better solution for the package long term. I'm sure @Tina815 will be looking over this soon and can help get things sorted 😄

**Comment by Moohan** [comment]
Rebased to development in #98.

**Pull request closed without merging**
